### PR TITLE
Fixed .bitmap files and added a generator for them

### PR DESCRIPTION
**Pull request by d4rkd3v1l**
The supplied .bitmap files were not working as expected. E.g. `So` contained letters like "f". 
So I re-created the files using Swift, parsing the UnicodeData, creating Charsets from it and save them as .bitmaps, so they can be used in the plugin.

### CODE REVIEW

**Comment by alextov** [comment]
@d4rkd3v1l Thank you!

**Comment by d4rkd3v1l** [comment]
@alextov You're welcome. I didn't increase the version number, could take care of that?

**Comment by d4rkd3v1l** [comment]
@alextov Could you please bump the version, so that I can switch my Podfile back to your branch? Thx! :-)

**Comment by alextov** [comment]
@d4rkd3v1l Updated and published a new release, should be good now.

**Comment by d4rkd3v1l** [comment]
@alextov Thanks! Even though your changes seem reasonably to me, CocoaPods still delivers 1.0.2. Is it possible that there went something wrong, when pushing it to CocoaPods? (I never did my own pod, so I don't really know what could have gone wrong here.. just a guess ;-))

**Comment by alextov** [comment]
@d4rkd3v1l Could you try performing `pod update` and `pod repo update`? New versions should be pulled directly from github.

**Comment by d4rkd3v1l** [comment]
@alextov Unfortunately not, I already tried this.
After `pod repo update` and `pod update MoreCharacterSets`:
> Installing MoreCharacterSets 1.0.2 (was 1.0.2)

**Comment by d4rkd3v1l** [comment]
@alextov Did you `pod trunk push MoreCharacterSets.podspec`? I think thats the missing step :-)

**Comment by alextov** [comment]
@d4rkd3v1l Thanks for the heads-up! I was convinced that CP would pull it automatically, but I guess it makes sense that it didn’t since they use a master repo with podspecs for distribution. Please check again now, it should pull the latest version.

**Pull request merged**
